title = ""
baseURL = "https://windupariships.com/"
languageCode = "en-us"
theme = "ananke"

enableInlineShortcodes = true
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = "UA-180233307-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/windupairships-logo.svg"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/billzajac"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/bill-zajac/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/zeppelin.png"
  recent_posts_number = 2
